#!/bin/bash
# CREATE A NEW SPECFEM RUN FOLDER BASED ON EVENT ID NUMBER
EVENT_ID=$1

RUNFOLDER=`pwd`
cd ${RUNFOLDER}
#echo LOADING MODULES
#source ./loadModules.sh

PRIMER=${RUNFOLDER}/PRIMER
CMTSOLUTION=${PRIMER}/CMTSOLUTION_FILES/${EVENT_ID}CMTSOLUTION

# CHECK IF CMTSOLUTION FILE EXISTS
if [ ! -f ${CMTSOLUTION} ]
then
	echo ${CMTSOLUTION} DOES NOT EXIST
	exit
fi
# CHECK IF RUNFOLDER ALREADY EXISTS
if [ -d RUNS/${EVENT_ID} ]
then
	echo RUNFOLDER ALREADY EXISTS
	exit
fi

echo LOADING MODULES
source ${RUNFOLDER}/loadModules.sh

echo CREATING FOLDER ${EVENT_ID}
cp -r ${PRIMER}/TEMPLATES/specfemMasterTemplate ${EVENT_ID}

echo COPYING STATION FILE
cp ${PRIMER}/STATIONS ${EVENT_ID}/DATA/

echo COPYING CMTSOLUTION
cp ${CMTSOLUTION} ${EVENT_ID}/DATA/
cp ${EVENT_ID}/DATA/${EVENT_ID}CMTSOLUTION ${EVENT_ID}/DATA/CMTSOLUTION

echo COPYING RUNSCRIPTS
cp ${PRIMER}/RUNSCRIPTS/* ${EVENT_ID}/

echo MOVING TO RUNS
mv ${EVENT_ID}/ RUNS/
cd RUNS/${EVENT_ID}

echo REPLACING RUNSCRIPT NAME
SEDCOMMAND="sed -i '3s/.*/#SBATCH --job-name="${EVENT_ID}"/' simulation_run.sh"
eval ${SEDCOMMAND} 

echo RUNNING MAKE
./configure FC=ftn CC=cc CXX=CC MPIFC=ftn MPICC=cc MPICXX=CC --with-mpi
make clean
make -s

