#!/bin/bash
export PYTHONPATH=$PYTHONPATH:/scale_wlg_persistent/filesets/project/nesi00263/PyPackages/seisflows3
export PYTHONPATH=$PYTHONPATH:/scale_wlg_persistent/filesets/project/nesi00263/PyPackages/seisflows-super
