# This is a Config file to control the behavior of semslicer
# NOTE: domain and region_1 are required parameters.
# Additional region_i can be included, where 1 <= i <= inf
# Units can be meters [m] or kilometers [km]; will be scaled to meters
# NOTE: Try to ensure overlap between depth values so that there are no gaps
data:
    - vp
    - vs
    - rho
    - qmu
    - qkappa
domain:
  xmin: 170.
  xmax: 635.
  ymin: 5286.
  ymax: 5905.
  units: km
region_1:
  tag: crust_1
  zmin: -12.
  zmax: -7.
  dx: 1.
  dy: 1.
  dz: .25
region_2:
  tag: crust_2
  zmin: -17.
  zmax: -12.
  dx: 1.
  dy: 1.
  dz: .25
region_3:
  tag: crust_3
  zmin: -22.
  zmax: -17.
  dx: 1.
  dy: 1.
  dz: .25
region_4:
  tag: crust_4
  zmin: -27.
  zmax: -22.
  dx: 1.
  dy: 1.
  dz: .25
region_5:
  tag: crust_5
  zmin: -32.
  zmax: -27.
  dx: 1.
  dy: 1.
  dz: .25
region_6:
  tag: crust_6
  zmin: -37.
  zmax: -32.
  dx: 1.
  dy: 1.
  dz: .25
region_7:
  tag: crust_7
  zmin: -42.
  zmax: -37.
  dx: 1.
  dy: 1.
  dz: .25
region_7:
  tag: crust_8
  zmin: -47.
  zmax: -42.
  dx: 1.
  dy: 1.
  dz: .25
