# This is a Config file to control the behavior of semslicer
# NOTE: domain and region_1 are required parameters.
# Additional region_i can be included, where 1 <= i <= inf
# Units can be meters [m] or kilometers [km]; will be scaled to meters
# NOTE: Try to ensure overlap between depth values so that there are no gaps
data:
    - vp
    - vs 
    - rho
    - qmu
    - qkappa
domain:
  xmin: 170.
  xmax: 635.
  ymin: 5286.
  ymax: 5905.
  units: km
region_1:
  tag: mantle
  zmin: -100.
  zmax: -40.
  dx: 4.
  dy: 4.
  dz: 4.


