# This is a Config file to control the behavior of semslicer
# NOTE: domain and region_1 are required parameters.
# Additional region_i can be included, where 1 <= i <= inf
# Units can be meters [m] or kilometers [km]; will be scaled to meters
# NOTE: Try to ensure overlap between depth values so that there are no gaps
domain:
  xmin: 170.
  xmax: 635.
  ymin: 5286.
  ymax: 5905.
  units: km
region_1:
  tag: shallow
  zmin: -12.
  zmax: 3.
  dx: 6.
  dy: 6.
  dz: 3.
region_2:
  tag: crust
  zmin: -50.
  zmax: -10.
  dx: 12.
  dy: 12.
  dz: 10.
region_3:
  tag: mantle
  zmin: -400.
  zmax: -30.
  dx: 24.
  dy: 24.
  dz: 30.


