# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#
#                 Seisflows YAML Parameter File and Path Input
#
#  For NoneType, set variables to `None` or `null`. For infinity, set to `inf`
#
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#
# These modules correspond to the structure of the source code, and determine
# SeisFlows' behavior at runtime. Check the source code directory for available 
# module names. Each module will require its own set of sub parameters. 
#
# To fill this parameter file with docstrings and default values, run:
#
# > seisflows configure
#
#                                    MODULES
#                                    -------
#
# WORKFLOW:    The method for running SeisFlows. Equivalent to main()
# SOLVER:      External numerical solver to use for waveform simulations.
# SYSTEM:      Computer architecture of the system being used to run SeisFlows
# OPTIMIZE:    Optimization algorithm for the inverse problem
# PREPROCESS:  Preprocessing schema for waveform data
# POSTPROCESS: Postprocessing schema for kernels and gradients
#
# ==============================================================================
WORKFLOW: inversion
SOLVER: specfem3d
SYSTEM: maui
OPTIMIZE: LBFGS 
PREPROCESS: pyatoa
POSTPROCESS: base

# ==============================================================================
#
#                                     SYSTEM                                    
#                                     ------                                    
#
# TITLE (str):
#    The name used to submit jobs to the system, defaults to the name of the
#    working directory
# WALLTIME (float):
#    Maximum job time in minutes for main SeisFlows job
# TASKTIME (float):
#    Maximum job time in minutes for each SeisFlows task
# NTASK (int):
#    Number of separate, individual tasks. Also equal to the number of desired
#    sources in workflow
# NPROC (int):
#    Number of processor to use for each simulation
# PRECHECK (list):
#    A list of parameters that will be displayed to stdout before 'submit' or
#    'resume' is run. Useful for manually reviewing important parameters prior
#    to system submission
# NTASKMAX (int):
#    Limit on the number of concurrent tasks in array
# NODESIZE (int):
#    The number of cores per node defined by the system
# SLURMARGS (str):
#    Any optional, additional SLURM arguments that will be passed to the
#    SBATCH scripts
# ENVIRONS (str):
#    Optional environment variables to be provided in thefollowing format
#    VAR1=var1,VAR2=var2...
# ACCOUNT (str):
#    The account name to submit jobs under
# NODES (int):
#    The number of nodes to use per job. Rough estimate would be
#    NPROC//NODESIZE
# CPUS_PER_TASK (int):
#    Multiple CPUS per task allows for multithreading jobs
# MAIN_CLUSTER (str):
#    Name of main cluster for job submission
# MAIN_PARTITION (str):
#    Name of partition on main cluster
# ANCIL_CLUSTER (str):
#    Name of ancillary cluster for prepost tasks
# ANCIL_PARTITION (str):
#    Name of ancillary partition for prepost tasks
# ANCIL_TASKTIME (float):
#    Tasktime for prepost jobs on ancillary nodes
# MPIEXEC (str):
#    Function used to invoke parallel executables

# ==============================================================================
TITLE: example
WALLTIME: 60
TASKTIME: 5
NTASK: 2
NPROC: 40
PRECHECK:
    - TITLE
    - BEGIN
    - END
    - WALLTIME
NTASKMAX: 100
NODESIZE: 40
SLURMARGS: ''
ENVIRONS: ''
ACCOUNT: gns03247
NODES: 1
CPUS_PER_TASK: 1
MAIN_CLUSTER: maui
MAIN_PARTITION: nesi_research
ANCIL_CLUSTER: maui_ancil
ANCIL_PARTITION: nesi_prepost
ANCIL_TASKTIME: null
MPIEXEC: srun

# ==============================================================================
#
#                                   PREPROCESS                                  
#                                   ----------                                  
#
# UNIT_OUTPUT (str):
#    Data units. Must match the synthetic output of external solver.
#    Available: ['DISP': displacement, 'VEL': velocity, 'ACC': acceleration]
# MIN_PERIOD (float):
#    Minimum filter corner in seconds
# MAX_PERIOD (float):
#    Maximum filter corner in seconds
# CORNERS (int):
#    Number of filter corners
# CLIENT (str):
#    Client name for ObsPy FDSN data gathering
# START_PAD (float):
#    For data gathering; time before origin time to gather. START_PAD >= T_0
#    in SPECFEM constants.h.in. Positive values only
# END_PAD (float):
#    For data gathering; time after origin time to gather. END_PAD >= NT * DT
#    (of Par_file). Positive values only
# ROTATE (bool):
#    Rotate waveform components NEZ -> RTZ
# ADJ_SRC_TYPE (str):
#    Adjoint source type to use. Available: ['cc': cross-correlation, 'mt':
#    multitaper, wav: waveform']
# PYFLEX_PRESET (str):
#    Parameter map for Pyflex config. For available choices, see Pyatoa docs
#    page
# FIX_WINDOWS (bool or str):
#    Time window evaluation: available: [True, False, 'ITER', 'ONCE'] True:
#    Same windows for all but i01s00; False: New windows at each evaluation;
#    'ITER': New windows at first evaluation of each iter; 'ONCE': New windows
#    at first evaluation of workflow
# PLOT (bool):
#    Plot waveforms and maps as .pdf files
# SNAPSHOT (bool):
#    Copy ASDFDataSets on disk for data redundancy
# LOGGING (str):
#    Log level. Available: ['null': no logging, 'warning': warnings only,
#    'info': task tracking, 'debug': log everything]

# ==============================================================================
UNIT_OUTPUT: DISP
MIN_PERIOD: 10
MAX_PERIOD: 30 
CORNERS: 4
CLIENT: GEONET
START_PAD: 20
END_PAD: 400
ROTATE: False
ADJ_SRC_TYPE: cc
PYFLEX_PRESET: default 
FIX_WINDOWS: False
PLOT: True
SNAPSHOT: True
LOGGING: DEBUG

# ==============================================================================
#
#                                     SOLVER                                    
#                                     ------                                    
#
# MATERIALS (str):
#    Material parameters used to define model. Available: ['ELASTIC': Vp, Vs,
#    'ACOUSTIC': Vp, 'ISOTROPIC', 'ANISOTROPIC']
# DENSITY (str):
#    How to treat density during inversion. Available: ['CONSTANT': Do not
#    update density, 'VARIABLE': Update density]
# COMPONENTS (str):
#    Components used to generate data, formatted as a single string, e.g. ZNE
#    or NZ or E
# SOLVERIO (int):
#    The format external solver files. Available: ['fortran_binary', 'adios']
# NT (float):
#    Number of time steps set in the SPECFEM Par_file
# DT (float):
#    Time step or delta set in the SPECFEM Par_file
# FORMAT (float):
#    Format of synthetic waveforms used during workflow, available options:
#    ['ascii', 'su']
# SOURCE_PREFIX (str):
#    Prefix of SOURCE files in path SPECFEM_DATA. Available ['CMTSOLUTION',
#    FORCESOLUTION']

# ==============================================================================
MATERIALS: ELASTIC 
DENSITY: CONSTANT
COMPONENTS: ZNE
SOLVERIO: fortran_binary
NT: 5000
DT: .0725
FORMAT: ascii
SOURCE_PREFIX: CMTSOLUTION

# ==============================================================================
#
#                                  POSTPROCESS                                  
#                                  -----------                                  
#
# SMOOTH_H (float):
#    Gaussian half-width for horizontal smoothing in units of meters. If 0.,
#    no smoothing applied
# SMOOTH_V (float):
#    Gaussian half-width for vertical smoothing in units of meters
# TASKTIME_SMOOTH (int):
#    Large radii smoothing may take longer than normal tasks. Allocate
#    additional smoothing task time as a multiple of TASKTIME

# ==============================================================================
SMOOTH_H: 0.
SMOOTH_V: 0.
TASKTIME_SMOOTH: 1

# ==============================================================================
#
#                                    OPTIMIZE                                   
#                                    --------                                   
#
# LINESEARCH (str):
#    Algorithm to use for line search, see seisflows.plugins.line_search for
#    available choices
# PRECOND (str):
#    Algorithm to use for preconditioning gradients, see
#    seisflows.plugins.preconds for available choices
# STEPCOUNTMAX (int):
#    Max number of trial steps in line search before a change in line serach
#    behavior
# STEPLENINIT (float):
#    Initial line serach step length, as a fraction of current model
#    parameters
# STEPLENMAX (float):
#    Max allowable step length, as a fraction of current model parameters
# LBFGSMEM (int):
#    Max number of previous gradients to retain in local memory
# LBFGSMAX (int):
#    LBFGS periodic restart interval, between 1 and 'inf'
# LBFGSTHRESH (float):
#    LBFGS angle restart threshold

# ==============================================================================
LINESEARCH: Backtrack
PRECOND:
STEPCOUNTMAX: 10
STEPLENINIT: 0.05
STEPLENMAX: 0.5
LBFGSMEM: 3
LBFGSMAX: inf
LBFGSTHRESH: 0.0

# ==============================================================================
#
#                                    WORKFLOW                                   
#                                    --------                                   
#
# BEGIN (int):
#    First iteration of workflow, 1 <= BEGIN <= inf
# END (int):
#    Last iteration of workflow, BEGIN <= END <= inf
# RESUME_FROM (str):
#    Name of task to resume inversion from
# STOP_AFTER (str):
#    Name of task to stop inversion after finishing
# CASE (str):
#    Type of inversion, available: ['data': real data inversion, 'synthetic':
#    synthetic-synthetic inversion]
# SAVEMODEL (bool):
#    Save final model files after each iteration
# SAVEGRADIENT (bool):
#    Save gradient files after each iteration
# SAVEKERNELS (bool):
#    Save event kernel files after each iteration
# SAVETRACES (bool):
#    Save waveform traces after each iteration
# SAVERESIDUALS (bool):
#    Save waveform residuals after each iteration
# SAVEAS (str):
#    Format to save models, gradients, kernels. Available: ['binary': save
#    files in native SPECFEM .bin format, 'vector': save files as NumPy .npy
#    files, 'both': save as both binary and vectors]
# VERBOSE (bool):
#    Provide detailed statements to the output logs

# ==============================================================================
BEGIN: 1
END: 1
RESUME_FROM: 
STOP_AFTER: line_search
CASE: synthetic
SAVEMODEL: True
SAVEGRADIENT: True
SAVEKERNELS: False
SAVETRACES: False
SAVERESIDUALS: False
SAVEAS: binary
VERBOSE: True

# ==============================================================================
#
#                                     PATHS                                     
#                                     -----                                     
#
# SCRATCH:
#    scratch path to hold temporary data during workflow
# OUTPUT:
#    directory to save workflow outputs to disk
# SYSTEM:
#    scratch path to hold any system related data
# LOCAL:
#    path to local data to be used during workflow
# PREPROCESS:
#    scratch path to store waveform data and figures
# DATA:
#    path to data available to workflow
# SOLVER:
#    scratch path to hold solver working directories
# SPECFEM_BIN:
#    path to the SPECFEM binary executables
# SPECFEM_DATA:
#    path to the SPECFEM DATA/ directory containing the 'Par_file', 'STATIONS'
#    file and 'CMTSOLUTION' files
# MASK:
#    Directory to mask files for gradient masking
# OPTIMIZE:
#    scratch path to store data related to nonlinear optimization
# MODEL_INIT:
#    Initial model to be used for workflow
# MODEL_TRUE:
#    Target model to be used for PAR.CASE == 'synthetic'
# FUNC:
#    scratch path to store data related to function evaluations
# GRAD:
#    scratch path to store data related to gradient evaluations
# HESS:
#    scratch path to store data related to Hessian evaluations

# ==============================================================================
PATHS:
    DATA:
    SPECFEM_DATA: ./utils/specfem3d/DATA
    SPECFEM_BIN: ./utils/specfem3d/bin 
    MODEL_INIT: ./utils/specfem3d/OUTPUT_FILES_HH/DATABASES_MPI
    MODEL_TRUE: ./utils/specfem3d/OUTPUT_FILES_LAYERED/DATABASES_MPI
# ==============================================================================
# !!! The paths below are default values and do not need to be changed !!!
# ==============================================================================
    SCRATCH: ./scratch
    OUTPUT: ./output 
    LOCAL:
    MASK:
    SOLVER: ./scratch/solver 
    SYSTEM: ./scratch/system 
    PREPROCESS: ./scratch/preprocess 
    OPTIMIZE: ./scratch/optimize 
    FUNC: ./scratch/evalfunc 
    GRAD: ./scratch/evalgrad 
    HESS: ./scratch/evalhess 
