syntax on
set mouse=a
set is
set hls
set key=
set noai
set expandtab
filetype plugin indent on
set tabstop=4
set shiftwidth=4
set softtabstop=0 noexpandtab
set colorcolumn=81
set nonumber
highlight LineNr ctermfg=green
colorscheme slate
